# Generated by Django 3.2 on 2022-07-11 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_auto_20220711_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='users',
        ),
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(related_name='todos', through='todos.UserTodos', to=settings.AUTH_USER_MODEL),

        )
    ]
