# Generated by Django 3.2 on 2022-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertodos',
            old_name='todos',
            new_name='todo',
        ),
    ]
